### ISSUE TITLE
Peaks don't handle Nans well

### ISSUE THREAD

**Issue by jonathanjfshaw** [timeflux/timeflux_dsp#11]
If the data you supply to LocalDetect contains NaNs, you get a lot of Runtime warnings because it tries to compare a NaN with a float.

Let's filter out NaNs when doing peak detection.

**Comment by bertrandlalo** [comment]
As discussed in your PR [here](https://github.com/timeflux/timeflux_dsp/pull/18), and in some others you opened with the same claim being 'when there is NaN in the data, if fails/warns...'. My opinion is that the user should handle NaNs separately.
