### ISSUE TITLE
Classifier node

### ISSUE THREAD

**Issue by jonathanjfshaw** [timeflux/timeflux_dsp#16]
The discretizer works well for collapsing numeric values into bands, but sometimes we want to classify data using arbitrary rules, possibly combining multiple data streams. This is also useful for event generation.

I have a classifier node that works like a Expression node but applies labels based on expressions. If you like it, I can clean up and add tests.

**Comment by jonathanjfshaw** [comment]
It's possible we'll want to change the implementation depending on https://github.com/timeflux/timeflux/issues/64

**Comment by bertrandlalo** [comment]
I don't understand what this issue is about. Can you please explain ?

**Comment by bertrandlalo** [comment]
Ok, now I see the related PR. 
Please, do not open issues when you wish to add a new feature. 
Do PR instead where you should clearly explain your use-case.  Issues should be reserved for existing code bugs/improvements. 
Hence, I'm closing  this one and I'll have a look at the PR instead.
