### ISSUE TITLE
Deprecated fftpack version in nodes/spectral.py

### ISSUE THREAD

**Issue by tonythree** [timeflux/timeflux_dsp#19]
Hi, using timeflux_dsp.nodes.spectral gives me an error:
```
 File "/Users/antonio/repo/hands-free-drone/EEGApi/venv/lib/python3.7/site-packages/timeflux_dsp/nodes/spectral.py", line 7, in <module>
    from scipy.signal.spectral import fftpack
ImportError: cannot import name 'fftpack' from 'scipy.signal.spectral'
```
Checking a bit about the error, I found this https://docs.scipy.org/doc/scipy/reference/fftpack.html.
I propose changing line 7 on spectral.py, from:
```from scipy.signal.spectral import fftpack```
to:
```from scipy import fft as fftpack```
or simply:
```from scipy import fft```
and changing fftpack -> fft in the following lines.
I can open a PR for that, if you find it necessary/interesting.

**Comment by mesca** [comment]
Thanks for pointing that out. Feel free to open a PR. I let @bertrandlalo take the lead as she is the maintainer for this plugin.

**Comment by mesca** [comment]
Fixed.
